# Generated by Django 5.1.7 on 2025-04-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
