# Generated by Django 5.1.7 on 2025-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_remove_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_template',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_templates',
            field=models.ManyToManyField(blank=True, to='cvapp.resumetemplate'),
        ),
    ]
