# Generated by Django 5.2 on 2025-05-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_remove_profile_resume_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='About',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='College',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Github_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Pin_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Work_experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scholl_location',
        ),
        migrations.RemoveField(
            model_name='resumetemplate',
            name='template_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='school_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='template_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificate',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profilepic/default.jpg', null=True, upload_to='profilepic/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
